### ISSUE TITLE
Email Remake

### ISSUE THREAD

**Issue by jasmine-schoch** [getgoji/goji-chrome-extension#35]
Try to get updated data in readable format,

in email:

- [x] explain what we want
- [x] what our purpose is
- [x] link existing code
- [x] Give credit! link back to original page!

RAW DATA IN CSV/SHEETS FORMAT

**Comment by jasmine-schoch** [comment]
Company scores: becca@remake.world
Report: chelsey@remake.world

**Comment by microBob** [comment]
- First attempt email sent to emails above.
- Consider doing a follow-up email on May 2nd (1 week after the first email)
- Add info@remake.world to the new email (general online email)

**Comment by jasmine-schoch** [comment]
follow up email written (to be sent once computer is back online)

**Comment by jasmine-schoch** [comment]
Response received! Meeting in progress of being set up.
