### ISSUE TITLE
[FEATURE]: More Info button should open in new tab

### ISSUE THREAD

**Issue by microBob** [getgoji/goji-chrome-extension#47]
### What will this feature resolve?

More Info button currently overwrites current page

### Describe the solution you'd like

Open in new tab instead

### Do you plan to solve this issue yourself?

Yes

**Comment by kjy5** [comment]
https://www.freecodecamp.org/news/how-to-open-a-link-in-a-new-tab/#:~:text=You%20can%20use%20the%20target,opening%20anchor%20tag%20like%20this.

**Comment by microBob** [comment]
completed with #70
